[project]
name = "instascraper"
version = "0.1.0"
description = "A simple scraper to pull reels for instagram users"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["requests>=2.32.4", "tenacity>=9.1.2"]
